yarnPath: "../../.yarn/releases/yarn-3.6.3.cjs"
cacheFolder: "../../.yarn/cache"
nodeLinker: node-modules
# nmHoistingLimits: workspaces
npmPublishAccess: "public"
npmPublishRegistry: "https://registry.npmjs.org"
npmAuthToken: "#{NODE_AUTH_TOKEN}#"
