version: "3.8"
services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # container_name: medusa-postgres
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    # container_name: medusa-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:5050
    depends_on:
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    # container_name: medusa-redis

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
    links:
      - redis
    ports:
      - 8085:80

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      TZ: Europe/Zagreb
