version: "3.8"
services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # container_name: medusa-postgres
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    # container_name: medusa-redis
