name: Release

on:
  release:
    types: [published]

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  publish-medusa-plugin-store-credit:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "packages/medusa-plugin-store-credit/yarn.lock"

      - uses: cschleiden/replace-tokens@v1
        with:
          files: "packages/medusa-plugin-store-credit/.yarnrc.yml"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # manually running prepare script because yarn v3 doesn't run it when publishing like npm does
      - run: cd packages/medusa-plugin-store-credit && yarn install && yarn run prepare && yarn npm publish
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # doesn't work with yarn v3
